server.port=8082
spring.application.name=product-service
spring.data.mongodb.uri=mongodb://root:DBVWiYdDoMnfWmK@localhost:27017/product_db?authSource=admin

management.endpoints.web.exposure.include=health
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [cid=%X{cid}] - %msg%n
logging.level.vn.demo=INFO
