server.port=8081
spring.application.name=auth-service
spring.data.mongodb.uri=mongodb://root:DBVWiYdDoMnfWmK@localhost:27017/auth_db?authSource=admin

app.jwt.secret=${JWT_SECRET:demo-bai4-lab-secret-change-me-32chars-min}
app.jwt.access-token.expiration-minutes=15
app.jwt.refresh-token.expiration-days=7

management.endpoints.web.exposure.include=health
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [cid=%X{cid}] - %msg%n
logging.level.vn.demo=INFO
