server.port=8083
spring.application.name=order-service
spring.data.mongodb.uri=mongodb://root:DBVWiYdDoMnfWmK@localhost:27017/order_db?authSource=admin

app.services.product.url=http://localhost:8082
app.services.notification.url=http://localhost:8084

management.endpoints.web.exposure.include=health
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [cid=%X{cid}] - %msg%n
logging.level.vn.demo=INFO
